import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/buttons.css";
import Header from "@/components/landing/Header";
import GlobalContextProvider from "@/context/GlobalContext";
import Footer from "@/sections/landing/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gravitas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContextProvider>
          <Header />
          {children}
          {/* <Footer /> */}
        </GlobalContextProvider>
      </body>
    </html>
  );
}
