import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/buttons.css";
import Header from "@/components/landing/Header";
import GlobalContextProvider from "@/context/GlobalContext";
import Footer from "@/sections/landing/Footer";
import { Toaster } from "@/components/ui/toaster";
import Head from "next/head";
const inter = Inter({ subsets: ["latin"] });
import GoogleAnalytics from "@/services/GA";

export const metadata: Metadata = {
  title: "Gravitas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>Gravitas&apos;24</title>
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
      </Head>
      <body className={inter.className}>
        {process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS && (
          <GoogleAnalytics ga_id={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS} />
        )}
        <Toaster />
        <GlobalContextProvider>
          <Header />
          {children}
          <Footer />
        </GlobalContextProvider>
      </body>
    </html>
  );
}
